"use strict";

/* ?????????????? */
"use strict";

/* =========================
   常量与默认数据
========================= */
const APP_VERSION = "1.5.8";
const SCHEMA_VERSION = 8;
const STORAGE_INDEX_KEY = "trpg-dm-assistant:index:v1";
const STORAGE_SLOT_PREFIX = "trpg-dm-assistant:slot:";
const STORAGE_API_KEY_PREFIX = "trpg-dm-assistant:api-key:";
const STORAGE_API_KEY_LEGACY = "trpg-dm-assistant:api-key";
const STORAGE_PREFS_KEY = "trpg-dm-assistant:prefs:v2";
const STORAGE_PREFS_KEY_LEGACY = "trpg-dm-assistant:prefs:v1";
const PHASES = new Set([
  "setup","character_ready","scenario_ready","awaiting_player_action","requesting_ai",
  "awaiting_check","rolling","requesting_ai_continuation","awaiting_node_confirmation","awaiting_ending_confirmation","campaign_ended","error"
]);
const TRANSITIONS = {
  setup:new Set(["character_ready","scenario_ready","awaiting_player_action"]),
  character_ready:new Set(["scenario_ready","awaiting_player_action","setup"]),
  scenario_ready:new Set(["character_ready","awaiting_player_action","setup"]),
  awaiting_player_action:new Set(["requesting_ai","awaiting_check","campaign_ended","setup"]),
  requesting_ai:new Set(["awaiting_player_action","awaiting_check","awaiting_node_confirmation","awaiting_ending_confirmation","error"]),
  awaiting_check:new Set(["rolling","requesting_ai_continuation","awaiting_player_action","error"]),
  rolling:new Set(["requesting_ai_continuation","awaiting_player_action","error"]),
  requesting_ai_continuation:new Set(["awaiting_player_action","awaiting_check","awaiting_node_confirmation","awaiting_ending_confirmation","error"]),
  awaiting_node_confirmation:new Set(["awaiting_player_action","campaign_ended","error"]),
  awaiting_ending_confirmation:new Set(["awaiting_player_action","campaign_ended","error"]),
  campaign_ended:new Set(["awaiting_player_action","setup"]),
  error:new Set(["requesting_ai","requesting_ai_continuation","awaiting_player_action","awaiting_check","setup"])
};
const STORAGE_LIMITS={maxSlots:30,maxMessages:1200,maxLogs:2000,maxProcessedRequestIds:500};
const MAX_API_RESPONSE_BYTES=2_000_000;
const MAX_IMPORT_DEPTH=30;
const MAX_IMPORT_NODES=100_000;
const MAX_IMPORT_STRING_LENGTH=250_000;
const MAX_IMPORTED_SCENARIO_NODES=400;
const MAX_IMPORTED_SCENARIO_CLUES=1200;
const MAX_TEMPORARY_NODES_TOTAL=24;
const MAX_TEMPORARY_NODES_PER_SCENE=10;
const MAX_CONSECUTIVE_SPATIAL_MOVES=4;
const MAX_CHECK_CHAIN_DEPTH=4;
const MAX_CONTEXT_MESSAGES=80;
const MAX_CONTEXT_CHARS=60_000;
const DEFAULT_CONTEXT_CHAR_BUDGET=24_000;
const DEFAULT_LORE_CHAR_BUDGET=6_000;
const RECOMMENDED_TEMPERATURE=0.45;
const DANGEROUS_KEYS=new Set(["__proto__","prototype","constructor"]);
const API_TRANSPORT_CONFIG_KEYS=new Set(["apiUrl","model","temperature","timeoutMs"]);
const SPATIAL_GENERIC_TERMS=["门","房间","走廊","楼梯","地道","通道","地下室","密室","大厅","仓库","入口","出口"];
const OFFICIAL_MODEL_OPTIONS=[{value:"deepseek-v4-flash",label:"DeepSeek V4 Flash（推荐）"},{value:"deepseek-v4",label:"DeepSeek V4"}];
const DEFAULT_CONFIG={system:"coc7",scenarioMode:"preset",ruleStrictness:"normal",worldBackground:"现代都市中的克苏鲁式调查",narrativeStyle:"克制、调查优先、强调可验证线索",contentBoundaries:"不描写露骨性内容；极端暴力以概括方式处理",apiUrl:"https://api.deepseek.com/chat/completions",model:"deepseek-v4-flash",temperature:RECOMMENDED_TEMPERATURE,timeoutMs:60_000,occupationSkillCap:80,nonOccupationSkillCap:60,contextCharBudget:DEFAULT_CONTEXT_CHAR_BUDGET,loreCharBudget:DEFAULT_LORE_CHAR_BUDGET,kpDebug:false};

function defaultDirectorState(){return{tension:1,maxTension:6,progress:0,sceneTurns:0,totalTurns:0,lastProgressTurn:0,activeThreats:[],revealedTruths:[],pendingPressure:null,clocks:[]}}
function defaultOutcomes(){return{subject:"unknown",truth:"hidden",evidence:"none",threat:"active",investigator:"safe"}}
function defaultNavigationState(){return{visitedNodeIds:[],transitionHistory:[],temporaryNodeCount:0,temporaryNodeCountByScene:{},consecutiveSpatialMoves:0,lastConfirmedNodeId:null,lastMeaningfulNodeId:null,lastProgressMarker:"",recentLocationSignatures:[],loopInterventions:0}}
function defaultHintUsage(){return{count:0,lastAt:null,lastCost:null}}

const SCENARIO_LIBRARY = [
  {
    id:"scenario-old-house",title:"旧宅遗嘱",system:"coc7",mode:"structured",source:"内置原创示例",
    metadata:{estimatedMinutes:90,difficulty:"入门",tags:["调查","旧宅","遗嘱"]},
    briefing:{subtitle:"一封迟到的遗嘱，把你带回多年无人居住的旧宅。",era:"现代 · 秋季傍晚 · 城郊旧宅",playerRole:"你受律师委托，代表一位已故收藏家的远亲核对旧宅中的遗物与一份失踪的附录。",premise:"收藏家去世后，律师在整理遗产时发现遗嘱中提到的附录并未随文件入库。旧宅封存多年，只有一名老管家偶尔照看。",knownFacts:["附录可能记录一批未登记藏品。","旧宅长期空置，但水电仍由遗产账户维持。","律师要求你在今晚完成初步核对并带回可验证的记录。"],caseObjectives:["确认遗嘱附录是否仍在旧宅。","记录与遗产有关的异常情况并带回证据。"],opening:"傍晚六点多，你站在旧宅门厅。窗外天色正在迅速变暗，老管家把一串钥匙放在桌上，低声说：‘二楼西侧这些年没人进去。’",contentNote:"调查题材；包含轻度惊悚与遗体相关内容。"},
    initialLeads:[{id:"lead-will",text:"确认遗嘱附录的去向",status:"active"},{id:"lead-west-wing",text:"了解二楼西侧为何长期封闭",status:"active"}],
    initialQuestions:[{id:"q-annex",text:"遗嘱附录被谁取走或藏起？",status:"open"},{id:"q-caretaker",text:"老管家隐瞒了什么？",status:"open"}],
    director:{tone:"安静、压抑、逐步升级",hiddenTruth:"收藏家把附录和一件危险藏品一同封在西侧书房夹层；管家知道夹层存在，但不知道藏品性质。",pressurePlan:["停电或灯光异常","管家态度变化","西侧传来物体拖动声"]},
    loreCards:[{id:"lore-old-house",title:"旧宅布局",keywords:["旧宅","门厅","二楼","西侧","书房"],priority:10,content:"旧宅为两层砖木结构。门厅通向会客厅与楼梯；二楼西侧走廊尽头是收藏家的旧书房。书房多年封闭，门锁陈旧但完整。"}],
    chapters:[{id:"ch1",title:"旧宅调查",scenes:[{id:"scene-main",title:"入宅",nodes:[
      {id:"old-hall",title:"门厅",background:"旧宅门厅铺着暗色木地板。楼梯通往二楼，左侧是会客厅，老管家正在整理钥匙。",visibleDetails:["门厅桌上有一串贴着褪色标签的钥匙。","墙上挂着收藏家年轻时的肖像。"],goals:["建立调查方向","允许与管家交谈"],clues:[{id:"clue-key-tag",name:"褪色钥匙标签",description:"其中一枚钥匙标签写着‘西书房’，但标签背面有近期重新粘贴的痕迹。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-key-tag-auto",type:"automatic"}]}],npcs:[{id:"npc-caretaker",name:"老管家",description:"七十岁左右，谨慎而疲惫。",attitude:"礼貌但回避西侧话题"}],mandatoryChecks:[],optionalChecks:[{id:"hall-spot",label:"观察钥匙",system:"coc7",type:"skill",skillId:"spot_hidden",difficulty:"regular",visibility:"public",mandatory:false,reason:"仔细检查钥匙串与标签",purpose:"判断钥匙是否近期被动过",successText:"你注意到西书房钥匙标签背面有新胶痕。",failureText:"钥匙串看起来只是多年未整理的旧物。"}],exits:[{id:"hall-to-parlor",label:"去会客厅",targetNodeId:"old-parlor"},{id:"hall-to-upstairs",label:"上二楼",targetNodeId:"old-upstairs"}]},
      {id:"old-parlor",title:"会客厅",background:"会客厅家具都罩着防尘布，壁炉旁堆着几只封存纸箱。",visibleDetails:["一只纸箱贴有律师事务所封条。","壁炉灰烬看起来并不陈旧。"],goals:["提供遗产文件线索"],clues:[{id:"clue-fireplace",name:"近期灰烬",description:"壁炉里有近一周内燃烧过纸张的灰烬，其中夹着印有律师事务所抬头的纸角。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-fireplace-auto",type:"automatic"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[],exits:[{id:"parlor-to-hall",label:"返回门厅",targetNodeId:"old-hall"}]},
      {id:"old-upstairs",title:"二楼楼梯口",background:"楼梯尽头分成东西两条走廊。西侧明显更暗，尽头能看到一扇上锁的门。",visibleDetails:["西侧地毯上有一条较新的拖痕。"],goals:["把调查引向西侧书房"],clues:[{id:"clue-drag-mark",name:"地毯拖痕",description:"拖痕从西书房门口延伸到楼梯附近，像是近期搬动过沉重箱子。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-drag-auto",type:"automatic"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[],exits:[{id:"upstairs-to-study",label:"前往西书房",targetNodeId:"old-study"},{id:"upstairs-to-hall",label:"下楼",targetNodeId:"old-hall"}]},
      {id:"old-study",title:"西书房",background:"书房空气沉闷，书架靠墙排列。中央书桌覆盖着厚灰，但靠墙书架前的灰尘被扰动过。",visibleDetails:["书架底部有不自然的刮痕。"],goals:["发现夹层","取得遗嘱附录"],clues:[{id:"clue-hidden-panel",name:"书架夹层",description:"靠墙书架后有一个窄小夹层，里面藏着遗嘱附录和一只封蜡木盒。",hidden:true,protected:true,critical:true,acquisitionRoutes:[{id:"route-hidden-panel-check",type:"check",checkId:"study-spot"},{id:"route-hidden-panel-fail-forward",type:"failure_forward",checkId:"study-spot",cost:{tension:1}}]},{id:"clue-will-annex",name:"遗嘱附录",description:"附录列出一件未登记藏品：‘黑曜石圣像’，并注明不得公开展示。",hidden:true,protected:true,critical:true,acquisitionRoutes:[{id:"route-will-annex-clue",type:"clue",requiredClueId:"clue-hidden-panel"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[{id:"study-spot",label:"搜索书房",system:"coc7",type:"skill",skillId:"spot_hidden",difficulty:"regular",visibility:"public",mandatory:false,reason:"寻找被隐藏的夹层",purpose:"确认书架是否有机关或夹层",successText:"你发现书架底部刮痕与墙面空隙并不自然。",failureText:"你花了不少时间搜索，最终从书架下方松动的木板发现异常。",failureForward:true}],exits:[{id:"study-to-upstairs",label:"返回楼梯口",targetNodeId:"old-upstairs"}]}
    ]}]}],
    endings:[{id:"ending-report",title:"带着附录离开",summary:"你带着足够的信息离开旧宅，准备把遗嘱附录交给律师。",requiresAnyClueIds:["clue-will-annex"],minClues:1},{id:"ending-withdraw",title:"暂时撤离",summary:"你决定先离开旧宅，把今晚的异常情况记录下来。",alwaysAvailable:true}]
  },
  {
    id:"scenario-train",title:"无灯列车",system:"coc7",mode:"structured",source:"内置原创示例",
    metadata:{estimatedMinutes:75,difficulty:"普通",tags:["列车","失踪","调查"]},
    briefing:{subtitle:"午夜之后，一列不在时刻表上的旧式列车停进了封闭站台。",era:"现代 · 午夜 · 郊区铁路站",playerRole:"你是受铁路公司临时委托的调查人员，需要确认封闭站台为何出现未经调度的列车。",premise:"监控只拍到列车进站，没有拍到司机或乘客下车。列车编号属于二十年前已退役的车型。",knownFacts:["列车停在封闭的 4 号站台。","调度系统中没有这趟列车记录。","站务员拒绝独自靠近车厢。"],caseObjectives:["确认列车来源与车内情况。","寻找可以解释异常进站的证据。"],opening:"午夜零点四十分，你穿过已经熄灯的候车厅。玻璃门外，4 号站台上的旧式列车没有亮任何车灯，车门却半开着。",contentNote:"包含失踪、幽闭空间和超自然暗示。"},
    initialLeads:[{id:"lead-train",text:"检查无调度记录的列车",status:"active"},{id:"lead-control",text:"核对站内监控与调度异常",status:"active"}],
    initialQuestions:[{id:"q-driver",text:"司机和乘客去了哪里？",status:"open"},{id:"q-origin",text:"这列退役列车为何仍能进站？",status:"open"}],director:{tone:"幽闭、安静、机械噪音逐步异常",hiddenTruth:"列车在一次旧事故后被废弃，现象会重复事故前最后一段路线。",pressurePlan:["站台灯熄灭","广播自动播放旧时刻表","车门开始依次关闭"]},
    loreCards:[{id:"lore-train-history",title:"退役列车资料",keywords:["列车","车号","退役","事故","调度"],priority:9,content:"该车型在二十年前的一次重大线路事故后分批退役。事故档案只在铁路内部数据库保留摘要。"}],
    chapters:[{id:"train-ch1",title:"封闭站台",scenes:[{id:"train-scene",title:"午夜进站",nodes:[
      {id:"train-platform",title:"4号站台",background:"站台照明只剩应急灯，旧列车停在轨道旁，最近一节车厢门半开。",visibleDetails:["车身编号被灰尘覆盖了一部分。","站台边缘有新鲜的金属摩擦痕迹。"],goals:["调查列车外部","选择是否上车"],clues:[{id:"train-number",name:"退役车号",description:"擦去灰尘后可以确认列车编号属于二十年前已退役车型。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-train-number-auto",type:"automatic"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[],exits:[{id:"platform-to-car",label:"进入最近车厢",targetNodeId:"train-car"}]},
      {id:"train-car",title:"昏暗车厢",background:"车厢里只有少量应急灯。座位上散落着旧报纸和几件个人物品。",visibleDetails:["车厢尽头的连接门偶尔传来敲击声。"],goals:["调查乘客遗留物"],clues:[{id:"train-ticket",name:"旧车票",description:"一张车票日期与二十年前事故当天一致，目的地正是这座车站。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-train-ticket-check",type:"check",checkId:"train-spot"},{id:"route-train-ticket-fail-forward",type:"failure_forward",checkId:"train-spot",cost:{tension:1}}]},{id:"train-map-fragment",name:"线路图残片",description:"残片标记了一段如今已经废弃的支线。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-train-map-check",type:"check",checkId:"train-spot"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[{id:"train-spot",label:"搜索车厢",system:"coc7",type:"skill",skillId:"spot_hidden",difficulty:"regular",visibility:"public",mandatory:false,reason:"检查座位、行李架和遗留物",purpose:"寻找能确认列车历史的证据",successText:"你在座椅缝隙和旧报纸下发现了异常遗留物。",failureText:"你花了较长时间翻找，最终仍找到一张被压在座位底下的旧车票。",failureForward:true}],exits:[{id:"car-to-platform",label:"返回站台",targetNodeId:"train-platform"},{id:"car-to-driver",label:"前往驾驶室",targetNodeId:"train-driver"}]},
      {id:"train-driver",title:"驾驶室",background:"驾驶室没有人，控制台部分仪表仍亮着。一本纸质行车日志摊在座位上。",visibleDetails:["速度表指针停在零，但里程计仍偶尔跳动。"],goals:["确认异常路线"],clues:[{id:"train-log",name:"行车日志",description:"最后一页记录的时间停在旧事故发生前几分钟，路线栏写着已经废弃的支线编号。",hidden:true,protected:true,critical:true,acquisitionRoutes:[{id:"route-train-log-auto",type:"automatic"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[],exits:[{id:"driver-to-car",label:"返回车厢",targetNodeId:"train-car"}]}
    ]}]}],endings:[{id:"train-report",title:"带证据撤离",summary:"你带着列车编号、车票与日志等证据离开封闭站台。",minClues:2},{id:"train-leave",title:"立即撤离",summary:"你判断继续停留风险过高，选择先撤离并封锁站台。",alwaysAvailable:true}]
  },
  {
    id:"scenario-lighthouse",title:"雾中灯塔",system:"coc7",mode:"structured",source:"内置原创示例",metadata:{estimatedMinutes:80,difficulty:"普通",tags:["海岸","灯塔","失联"]},
    briefing:{subtitle:"连续三晚，自动化灯塔在无人值守状态下发出错误信号。",era:"现代 · 冬季清晨 · 海岸灯塔",playerRole:"你受海事部门委托，前往已经自动化的灯塔检查错误信号与维护员失联事件。",premise:"灯塔一个月前改为远程控制，但最近三晚都在凌晨发送旧式摩尔斯求救信号。负责维护的技术员昨天失去联系。",knownFacts:["灯塔远程控制记录显示设备没有被手动切换。","维护员最后一次通话提到地下机房有积水。","海况正在恶化，中午之后可能无法乘船离开。"],caseObjectives:["找到维护员或确认其去向。","解释错误求救信号的来源。"],opening:"船把你送到礁石码头后立刻返航。雾很浓，灯塔顶部的灯在白天仍缓慢旋转。入口门没有上锁。",contentNote:"包含海难、失联与轻度超自然内容。"},initialLeads:[{id:"light-tech",text:"寻找失联维护员",status:"active"},{id:"light-signal",text:"追查错误求救信号",status:"active"}],initialQuestions:[{id:"light-q1",text:"谁在发送旧式求救信号？",status:"open"}],director:{tone:"潮湿、孤立、时间压力",hiddenTruth:"旧线路受海水侵蚀后重放了多年前遇难船只的求救录音，维护员进入地下机房后受伤被困。",pressurePlan:["潮位上涨","电力不稳","地下机房进水"]},loreCards:[{id:"light-lore",title:"灯塔系统",keywords:["灯塔","摩尔斯","机房","维护员"],priority:8,content:"灯塔曾使用独立无线电与继电器系统，自动化改造时大部分旧线路没有拆除，只与主电源隔离。"}],chapters:[{id:"light-ch",title:"灯塔调查",scenes:[{id:"light-sc",title:"雾中灯塔",nodes:[{id:"light-entry",title:"灯塔入口",background:"入口潮湿，工具架少了一套防水服。墙上维护表停在昨天上午。",visibleDetails:["通往地下机房的门边有泥水脚印。"],goals:["寻找维护员路线"],clues:[{id:"light-footprints",name:"泥水脚印",description:"脚印从入口一路通向地下机房，没有返回痕迹。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-light-footprints-auto",type:"automatic"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[],exits:[{id:"light-to-machine",label:"进入地下机房",targetNodeId:"light-machine"}]},{id:"light-machine",title:"地下机房",background:"机房地面积水已经没过鞋底。旧式继电器柜仍在发出间歇蜂鸣。",visibleDetails:["角落传来微弱敲击声。"],goals:["找到维护员","确认信号来源"],clues:[{id:"light-relay",name:"旧继电器录音回放",description:"旧继电器与录音模块意外重新通电，正在循环播放历史求救信号。",hidden:true,protected:true,critical:true,acquisitionRoutes:[{id:"route-light-relay-check",type:"check",checkId:"light-electrical"},{id:"route-light-relay-fail",type:"failure_forward",checkId:"light-electrical",cost:{tension:1}}]}],npcs:[{id:"light-tech-npc",name:"维护员陈旭",description:"腿部受伤，被倒下的设备架困在角落。",attitude:"虚弱但清醒"}],mandatoryChecks:[],optionalChecks:[{id:"light-electrical",label:"检查旧线路",system:"coc7",type:"skill",skillId:"electrical_repair",difficulty:"regular",visibility:"public",mandatory:false,reason:"确认异常信号由哪套设备发出",purpose:"追踪求救信号来源",successText:"你确认旧继电器柜正在向发射模块重复送出信号。",failureText:"线路非常混乱，但你最终从反复跳动的继电器上确认了大致来源。",failureForward:true}],exits:[{id:"machine-to-entry",label:"返回入口",targetNodeId:"light-entry"}]}]}]}],endings:[{id:"light-rescue",title:"救出维护员并报告故障",summary:"你救出维护员，并带回足够信息解释异常信号。",requiresAnyClueIds:["light-relay"],minClues:1},{id:"light-evacuate",title:"因海况撤离",summary:"你在海况进一步恶化前选择撤离。",alwaysAvailable:true}]},
  {
    id:"scenario-clinic",title:"夜诊档案",system:"coc7",mode:"structured",source:"内置原创示例",metadata:{estimatedMinutes:85,difficulty:"普通",tags:["诊所","档案","失踪"]},
    briefing:{subtitle:"一家停业诊所的档案室里，多出了一批不存在于登记系统中的病历。",era:"现代 · 夜间 · 已停业私人诊所",playerRole:"你受物业与警方联合委托，在正式封存前核对诊所档案并寻找失踪管理员留下的线索。",premise:"诊所因负责人失联而停业。物业清点时发现档案数量比系统记录多出十七份，其中部分患者姓名查无记录。",knownFacts:["失踪管理员最后一次刷卡记录在档案室。","诊所监控在失踪当晚中断四十分钟。","警方尚未把事件定性为刑事案件。"],caseObjectives:["确认异常病历来源。","寻找管理员失踪前留下的信息。"],opening:"卷闸门在身后落下，诊所大厅只亮着应急灯。档案室的门开着一条缝，里面有纸张翻动的声音。",contentNote:"包含医疗、失踪与轻度惊悚内容。"},initialLeads:[{id:"clinic-files",text:"核对异常病历",status:"active"},{id:"clinic-admin",text:"追查失踪管理员",status:"active"}],initialQuestions:[{id:"clinic-q",text:"不存在的患者档案从何而来？",status:"open"}],director:{tone:"洁净环境中的不协调感",hiddenTruth:"管理员发现负责人长期伪造试验记录并把真实档案藏在旧储藏室，失踪前试图留下证据。",pressurePlan:["应急灯熄灭","自动门锁死","旧打印机自行启动"]},loreCards:[{id:"clinic-lore",title:"诊所档案制度",keywords:["病历","档案","管理员","刷卡"],priority:8,content:"正式病历都有连续编号和电子索引。纸质档案若没有电子编号，通常意味着未按制度归档或被人为绕过。"}],chapters:[{id:"clinic-ch",title:"夜间核查",scenes:[{id:"clinic-sc",title:"停业诊所",nodes:[{id:"clinic-lobby",title:"诊所大厅",background:"大厅整洁得反常，接待台电脑已经断电。",visibleDetails:["管理员办公桌抽屉没有上锁。"],goals:["找到进入档案室的背景信息"],clues:[{id:"clinic-note",name:"管理员便签",description:"便签写着‘编号从 417 开始不对，旧储藏室还有原件’。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-clinic-note-auto",type:"automatic"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[],exits:[{id:"clinic-to-archive",label:"进入档案室",targetNodeId:"clinic-archive"}]},{id:"clinic-archive",title:"档案室",background:"金属档案柜排列整齐，靠墙有一台老式打印机。",visibleDetails:["一格档案柜的锁被反复撬动过。"],goals:["确认异常档案"],clues:[{id:"clinic-files-clue",name:"无编号病历",description:"十七份病历没有电子索引，内容涉及未经备案的长期观察。",hidden:true,protected:true,critical:true,acquisitionRoutes:[{id:"route-clinic-files-check",type:"check",checkId:"clinic-library"},{id:"route-clinic-files-fail",type:"failure_forward",checkId:"clinic-library",cost:{tension:1}}]}],npcs:[],mandatoryChecks:[],optionalChecks:[{id:"clinic-library",label:"整理档案",system:"coc7",type:"skill",skillId:"library_use",difficulty:"regular",visibility:"public",mandatory:false,reason:"从大量病历中找出登记异常",purpose:"确认异常病历的共同点",successText:"你迅速找出十七份没有电子索引的病历。",failureText:"整理耗费了很久，但编号断层最终还是暴露出来。",failureForward:true}],exits:[{id:"archive-to-lobby",label:"返回大厅",targetNodeId:"clinic-lobby"},{id:"archive-to-store",label:"前往旧储藏室",targetNodeId:"clinic-store"}]},{id:"clinic-store",title:"旧储藏室",background:"储藏室堆着废弃设备和纸箱，空气里有潮湿纸张的味道。",visibleDetails:["最里面的纸箱贴着管理员姓名。"],goals:["找到真实档案与管理员线索"],clues:[{id:"clinic-originals",name:"原始观察记录",description:"原始记录显示诊所负责人篡改了部分患者数据，并在报告中隐去了严重副作用。",hidden:true,protected:true,critical:true,acquisitionRoutes:[{id:"route-clinic-originals-auto",type:"automatic"}]}],npcs:[],mandatoryChecks:[],optionalChecks:[],exits:[{id:"store-to-archive",label:"返回档案室",targetNodeId:"clinic-archive"}]}]}]}],endings:[{id:"clinic-evidence",title:"带走证据",summary:"你找到足以交给警方的原始记录与异常病历。",requiresAnyClueIds:["clinic-originals"],minClues:2},{id:"clinic-leave",title:"退出诊所",summary:"你决定暂时离开并等待警方进一步处理。",alwaysAvailable:true}]},
  {
    id:"scenario-observatory",title:"山顶观测站",system:"coc7",mode:"structured",source:"内置原创示例",metadata:{estimatedMinutes:95,difficulty:"进阶",tags:["观测站","天文","失联"]},
    briefing:{subtitle:"自动观测站连续上传了不可能存在的星图，随后与山下失去联系。",era:"现代 · 冬夜 · 山顶天文观测站",playerRole:"你受研究机构委托，在暴雪封山前进入观测站恢复通讯并核对异常观测记录。",premise:"观测站最后一次正常通信在昨夜十一点。之后系统上传了三张无法对应当前天空的星图。值班研究员没有回应。",knownFacts:["山路将在数小时后因暴雪封闭。","观测站有独立柴油发电机。","异常星图来自主望远镜控制系统，而非外部上传。"],caseObjectives:["恢复观测站通讯。","找到值班研究员并确认异常星图来源。"],opening:"越野车在山下掉头离开。你推开观测站气密门时，里面一片漆黑，只有主控制室的显示器仍发着蓝光。",contentNote:"包含失联、寒冷环境与宇宙恐怖暗示。"},initialLeads:[{id:"obs-comms",text:"恢复通讯",status:"active"},{id:"obs-map",text:"调查异常星图",status:"active"}],initialQuestions:[{id:"obs-q",text:"主望远镜为什么记录了不存在的天空？",status:"open"}],director:{tone:"寒冷、孤立、理性逐渐失效",hiddenTruth:"主望远镜控制系统在一次软件故障后持续叠加历史观测缓存，形成一组看似不存在的星图；研究员发现异常后在穹顶检修时受伤。",pressurePlan:["温度下降","备用电源负载升高","穹顶机构卡死"]},loreCards:[{id:"obs-lore",title:"观测站系统",keywords:["望远镜","星图","缓存","控制系统","穹顶"],priority:9,content:"主望远镜会把原始观测帧缓存到本地阵列，再由控制软件生成星图。若时间戳或缓存索引损坏，理论上可能混入历史数据。"}],chapters:[{id:"obs-ch",title:"暴雪前夜",scenes:[{id:"obs-sc",title:"失联观测站",nodes:[{id:"obs-control",title:"主控制室",background:"显示器上反复刷新着一张陌生星图。通讯终端显示链路中断。",visibleDetails:["控制台旁有一杯已经结冰的咖啡。"],goals:["恢复基础信息","定位研究员"],clues:[{id:"obs-log",name:"系统错误日志",description:"日志显示星图生成任务多次读取了异常的旧缓存索引。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-obs-log-check",type:"check",checkId:"obs-computer"},{id:"route-obs-log-fail",type:"failure_forward",checkId:"obs-computer",cost:{tension:1}}]}],npcs:[],mandatoryChecks:[],optionalChecks:[{id:"obs-computer",label:"检查控制系统",system:"coc7",type:"skill",skillId:"computer_use",difficulty:"regular",visibility:"public",mandatory:false,reason:"检查星图生成与通讯日志",purpose:"确认异常星图是否来自系统内部",successText:"日志很快暴露出旧缓存索引被错误调用。",failureText:"系统结构复杂，但反复出现的缓存错误最终暴露了问题。",failureForward:true}],exits:[{id:"obs-to-dome",label:"前往望远镜穹顶",targetNodeId:"obs-dome"}]},{id:"obs-dome",title:"望远镜穹顶",background:"穹顶内温度接近冰点，巨大的望远镜停在异常角度。",visibleDetails:["检修平台附近掉着一只工作手套。"],goals:["找到研究员","确认机械状态"],clues:[{id:"obs-researcher",name:"受伤研究员",description:"值班研究员在检修穹顶机构时摔伤，无法自行移动，但神志清醒。",hidden:true,protected:true,acquisitionRoutes:[{id:"route-obs-researcher-auto",type:"automatic"}]},{id:"obs-cache-note",name:"缓存故障笔记",description:"研究员的笔记确认异常星图来自历史缓存叠加，而不是当前天空。",hidden:true,protected:true,critical:true,acquisitionRoutes:[{id:"route-obs-cache-note-clue",type:"clue",requiredClueId:"obs-researcher"}]}],npcs:[{id:"obs-npc",name:"研究员林若",description:"摔伤后被困在检修平台下方。",attitude:"焦虑但愿意配合"}],mandatoryChecks:[],optionalChecks:[],exits:[{id:"dome-to-control",label:"返回控制室",targetNodeId:"obs-control"}]}]}]}],endings:[{id:"obs-rescue",title:"救援并恢复通讯",summary:"你找到研究员并确认异常星图来自系统故障，随后恢复对外联系。",requiresAnyClueIds:["obs-cache-note"],minClues:1},{id:"obs-evacuate",title:"暴雪前撤离",summary:"你在道路彻底封闭前选择撤离。",alwaysAvailable:true}]}
];
